### PR TITLE
Expose Error in types.rb

### PR DESCRIPTION
**Pull request by Fryguy**

### CODE REVIEW

**Comment by chessbyte** [comment]
I think the [C code](https://github.com/ManageIQ/net_app_manageability/blob/master/ext/net_app_manageability/net_app_manageability.c#L546) has to change to do 

``` ruby
rb_eAPIError = rb_const_get(mNetAppManageability, rb_intern(exception_name));
```

instead of 

``` ruby
rb_eAPIError = rb_define_class_under(cAPI, exception_name, rb_eRuntimeError);
```

**Comment by Fryguy** [comment]
Oh hmm... It worked for the module,  so I assumed it would work for the
exception as well.   We'll have to test.

**Comment by chessbyte** [comment]
There is also an error/mismatch on the C side as it creates `NetAppManageability::API::Error` instead of `NetAppManageability::Error`

**Comment by Fryguy** [comment]
Ah yeah that's a bug... Thanks

**Comment by Fryguy** [comment]
@chessbyte Updated but I didn't test on a VM.

**Comment by chessbyte** [comment]
@Fryguy so, do you think that the exception class should be `NetAppManageability::Error` or `NetAppManageability::API::Error`?  I think the former may be clearer for the callers, unless we want multiple exception classes to show which layer the error is coming from (e.g. `NetAppManageability::Client::Error`).

**Comment by Fryguy** [comment]
Going to merge as is, and clean up in my next PR.

**Pull request merged**
